/* ------------------------------------------------------------------
   Vokabeldaten - ARC Kyoto, Topic 1 bis 3
   Aufbau je Zeile: [Abschnitt, Kana, Romaji, Bedeutung, Wortart]
   Wortart: N = Nomen, V = Verb, A = Adjektiv, leer = sonstiges
   ------------------------------------------------------------------ */

const ABSCHNITTE = {
  "1-1": { t: 1, nr: "§1", titel: "Vorstellung und Herkunft" },
  "1-2": { t: 1, nr: "§2", titel: "Räume und Orte" },
  "1-3": { t: 1, nr: "§3", titel: "これ・それ・あれ" },
  "1-4": { t: 1, nr: "§4", titel: "この・その・あの" },
  "2-1": { t: 2, nr: "§1", titel: "Uhrzeit und Tagesablauf" },
  "2-2": { t: 2, nr: "§2", titel: "Ferien und Termine" },
  "2-3": { t: 2, nr: "§3", titel: "Zeitangaben, Essen, Tätigkeiten" },
  "3-1": { t: 3, nr: "§1", titel: "Besitz und Einkauf" },
  "3-2": { t: 3, nr: "§2", titel: "Ort und Lage" },
  "4-1": { t: 4, nr: "§1", titel: "Verkehrsmittel und Reisezweck" },
  "4-3": { t: 4, nr: "§3", titel: "Vorlieben, Können und Wünsche" },
  "5-2": { t: 5, nr: "§2", titel: "Geben und Bekommen" },
  "5-3": { t: 5, nr: "§3", titel: "て-Form und höfliche Bitten" }
};

const ROH = [
/* ===== Topic 1 ===== */
["1-1","みなさん","minasan","alle zusammen, meine Damen und Herren","N"],
["1-1","～さん","~san","Höflichkeitsanhang für Namen",""],
["1-1","かいしゃいん","kaishain","Firmenangestellter","N"],
["1-1","せんせい","sensee","Lehrer, Lehrerin","N"],
["1-1","きょうし","kyooshi","Lehrkraft (Berufsbezeichnung)","N"],
["1-1","がくせい","gakusee","Schüler, Student","N"],
["1-1","～じん","~jin","Anhang für Nationalitäten",""],
["1-1","ちゅうごく","Chuugoku","China","N"],
["1-1","イタリア","Itaria","Italien","N"],
["1-1","にほん","Nihon","Japan","N"],
["1-1","アメリカ","Amerika","USA","N"],
["1-1","わたし","watashi","ich","N"],
["1-1","はい","hai","ja",""],
["1-1","いいえ","iie","nein",""],
["1-1","りゅうがくせい","ryuugakusee","ausländischer Student","N"],
["1-1","にほんごがっこう","nihongo-gakkoo","Japanischschule","N"],
["1-1","せんもんがっこう","senmon-gakkoo","Fachschule, Berufsfachschule","N"],
["1-1","だいがくせい","daigakusee","Universitätsstudent","N"],
["1-1","だいがく","daigaku","Universität","N"],
["1-1","ふどうさん","fudoosan","Immobilien, Immobilienbüro","N"],
["1-1","しゃいん","shain","Angestellter einer Firma","N"],
["1-1","しゅっしん","shusshin","Herkunft, Heimatort","N"],
["1-1","シャンハイ","Shanhai","Shanghai","N"],
["1-1","ベトナム","Betonamu","Vietnam","N"],
["1-1","フランス","Furansu","Frankreich","N"],
["1-1","カナダ","Kanada","Kanada","N"],
["1-1","ブラジル","Burajiru","Brasilien","N"],
["1-1","ペキン","Pekin","Peking","N"],
["1-1","びょういん","byooin","Krankenhaus","N"],
["1-1","いしゃ","isha","Arzt","N"],
["1-1","タイ","Tai","Thailand","N"],
["1-1","バンコク","Bankoku","Bangkok","N"],
["1-1","パリ","Pari","Paris","N"],
["1-1","オーストラリア","Oosutoraria","Australien","N"],
["1-1","シドニー","Shidonii","Sydney","N"],
["1-1","めいし","meeshi","Visitenkarte","N"],
["1-1","ともだち","tomodachi","Freund, Freundin","N"],
["1-1","シアトル","Shiatoru","Seattle","N"],
["1-1","くに","kuni","Land, Heimatland","N"],
["1-1","がっこう","gakkoo","Schule","N"],
["1-1","かいしゃ","kaisha","Firma","N"],

["1-2","リビング","ribingu","Wohnzimmer","N"],
["1-2","ひじょうぐち","hijooguchi","Notausgang","N"],
["1-2","ここ","koko","hier","N"],
["1-2","そこ","soko","da (beim Gesprächspartner)","N"],
["1-2","あそこ","asoko","dort drüben","N"],
["1-2","キッチン","kicchin","Küche","N"],
["1-2","トイレ","toire","Toilette","N"],
["1-2","（お）ふろ","(o)furo","Bad, Badewanne","N"],
["1-2","シャワールーム","shawaa-ruumu","Duschraum","N"],
["1-2","ランドリールーム","randorii-ruumu","Waschraum","N"],
["1-2","ごみおきば","gomi-okiba","Müllsammelplatz","N"],
["1-2","どこ","doko","wo","N"],
["1-2","それから","sorekara","und dann, außerdem",""],
["1-2","ばしょ","basho","Ort, Platz","N"],
["1-2","そと","soto","draußen, außen","N"],
["1-2","きつえんじょ","kitsuenjo","Raucherbereich","N"],
["1-2","かいぎしつ","kaigi-shitsu","Besprechungsraum","N"],
["1-2","じどうはんばいき","jidoo-hanbaiki","Getränkeautomat","N"],
["1-2","ものおき","monooki","Abstellraum","N"],
["1-2","うけつけ","uketsuke","Empfang, Rezeption","N"],
["1-2","しょくどう","shokudoo","Kantine, Mensa","N"],

["1-3","これ","kore","dies hier","N"],
["1-3","それ","sore","das da (beim Gesprächspartner)","N"],
["1-3","あれ","are","das dort drüben","N"],
["1-3","（お）みやげ","(o)miyage","Mitbringsel, Souvenir","N"],
["1-3","どうぞ","doozo","bitte sehr, hier bitte",""],
["1-3","（お）ちゃ","(o)cha","Tee","N"],
["1-3","カードキー","kaado-kii","Kartenschlüssel","N"],
["1-3","かんこく","Kankoku","Südkorea","N"],
["1-3","おかし","okashi","Süßigkeiten, Knabbereien","N"],
["1-3","コーヒー","koohii","Kaffee","N"],
["1-3","キーホルダー","kiihorudaa","Schlüsselanhänger","N"],
["1-3","マグネット","magunetto","Magnet","N"],
["1-3","かばん","kaban","Tasche","N"],
["1-3","ほん","hon","Buch","N"],
["1-3","ざっし","zasshi","Zeitschrift","N"],
["1-3","ジュース","juusu","Saft","N"],
["1-3","スマホ","sumaho","Smartphone","N"],
["1-3","ゲーム","geemu","Spiel, Videospiel","N"],
["1-3","しゃしん","shashin","Foto","N"],
["1-3","みかん","mikan","Mandarine","N"],
["1-3","ワイン","wain","Wein","N"],
["1-3","にんぎょう","ningyoo","Puppe","N"],
["1-3","くるま","kuruma","Auto","N"],
["1-3","なん","nan","was","N"],
["1-3","（お）てら","(o)tera","buddhistischer Tempel","N"],
["1-3","え","e","Bild, Gemälde","N"],
["1-3","～ご","~go","Sprache (Anhang)",""],
["1-3","えいご","eego","Englisch","N"],
["1-3","ファッション","fasshon","Mode","N"],
["1-3","かぎ","kagi","Schlüssel","N"],
["1-3","レストラン","resutoran","Restaurant","N"],
["1-3","ポイントカード","pointo-kaado","Punktekarte, Kundenkarte","N"],
["1-3","シェアハウス","shea-hausu","Wohngemeinschaft","N"],
["1-3","へや","heya","Zimmer","N"],
["1-3","さとう","satoo","Zucker","N"],
["1-3","しお","shio","Salz","N"],
["1-3","～ごうしつ","~goo-shitsu","Zimmernummer (Anhang)","N"],
["1-3","なんごうしつ","nan-goo-shitsu","welche Zimmernummer","N"],
["1-3","でんわばんごう","denwa-bangoo","Telefonnummer","N"],
["1-3","なんばん","nan-ban","welche Nummer","N"],

["1-4","この","kono","dieser hier",""],
["1-4","その","sono","dieser da",""],
["1-4","あの","ano","jener dort",""],
["1-4","ペン","pen","Stift","N"],
["1-4","ぼうし","booshi","Hut, Mütze","N"],
["1-4","コップ","koppu","Becher, Glas","N"],
["1-4","ひと","hito","Person, Mensch","N"],
["1-4","だれ","dare","wer","N"],
["1-4","シャツ","shatsu","Hemd","N"],
["1-4","コート","kooto","Mantel","N"],
["1-4","かさ","kasa","Regenschirm","N"],
["1-4","けしごむ","keshigomu","Radiergummi","N"],
["1-4","おんなのこ","onna-no-ko","Mädchen","N"],
["1-4","～ちゃん","~chan","vertrauliche Anrede, meist für Mädchen",""],
["1-4","かわいい","kawaii","süß, niedlich","Aい"],
["1-4","～くん","~kun","vertrauliche Anrede, meist für Jungen",""],
["1-4","おとこのこ","otoko-no-ko","Junge","N"],
["1-4","ノート","nooto","Heft, Notizbuch","N"],
["1-4","ボールペン","boorupen","Kugelschreiber","N"],
["1-4","きょうかしょ","kyookasho","Lehrbuch","N"],
["1-4","えんぴつ","enpitsu","Bleistift","N"],
["1-4","わすれもの","wasuremono","vergessener Gegenstand, Fundsache","N"],

/* ===== Topic 2 ===== */
["2-1","いま","ima","jetzt","N"],
["2-1","じかん","jikan","Zeit, Stunde","N"],
["2-1","はん","han","halb","N"],
["2-1","ロンドン","Rondon","London","N"],
["2-1","ニューヨーク","Nyuuyooku","New York","N"],
["2-1","パース","Paasu","Perth","N"],
["2-1","リオデジャネイロ","Riodejaneiro","Rio de Janeiro","N"],
["2-1","まち","machi","Stadt, Ort","N"],
["2-1","じゅぎょう","jugyoo","Unterricht","N"],
["2-1","はじまります","hajimarimasu","beginnen","V"],
["2-1","おわります","owarimasu","enden, zu Ende gehen","V",1],
["2-1","おきます","okimasu","aufstehen, aufwachen","V"],
["2-1","あさ","asa","Morgen","N"],
["2-1","まい～","mai~","jeden (Anhang)",""],
["2-1","ばん","ban","Abend","N"],
["2-1","ねます","nemasu","schlafen, schlafen gehen","V"],
["2-1","しごと","shigoto","Arbeit","N"],
["2-1","ギター","gitaa","Gitarre","N"],
["2-1","レッスン","ressun","Unterrichtsstunde, Kurs","N"],
["2-1","はたらきます","hatarakimasu","arbeiten","V"],
["2-1","ごぜん","gozen","vormittags","N"],
["2-1","ごご","gogo","nachmittags","N"],
["2-1","よる","yoru","Nacht","N"],
["2-1","としょかん","toshokan","Bibliothek","N"],
["2-1","びじゅつかん","bijutsukan","Kunstmuseum","N"],
["2-1","ゆうびんきょく","yuubinkyoku","Post","N"],
["2-1","ぎんこう","ginkoo","Bank","N"],
["2-1","べんきょうします","benkyoo-shimasu","lernen, studieren","V"],
["2-1","やすみます","yasumimasu","Pause machen, frei haben","V"],
["2-1","ホーチミン","Hoochimin","Ho-Chi-Minh-Stadt","N"],
["2-1","モスクワ","Mosukuwa","Moskau","N"],
["2-1","デパート","depaato","Kaufhaus","N"],
["2-1","カフェ","kafe","Café","N"],

["2-2","やすみ","yasumi","freier Tag, Urlaub","N"],
["2-2","カレンダー","karendaa","Kalender","N"],
["2-2","いつ","itsu","wann",""],
["2-2","テスト","tesuto","Test, Prüfung","N"],
["2-2","アルバイト","arubaito","Nebenjob","N"],
["2-2","ごみのひ","gomi-no-hi","Mülltag","N"],
["2-2","たんじょうび","tanjoobi","Geburtstag","N"],
["2-2","はるやすみ","haru-yasumi","Frühlingsferien","N"],
["2-2","なつやすみ","natsu-yasumi","Sommerferien","N"],
["2-2","ふゆやすみ","fuyu-yasumi","Winterferien","N"],
["2-2","ゴールデンウィーク","gooruden-wiiku","Golden Week","N"],
["2-2","うち／いえ","uchi / ie","Zuhause, Haus","N"],
["2-2","いきます","ikimasu","gehen, fahren","V"],
["2-2","きます","kimasu","kommen","V"],
["2-2","かえります","kaerimasu","nach Hause gehen, zurückkehren","V"],
["2-2","スーパー","suupaa","Supermarkt","N"],
["2-2","どこも","dokomo","nirgendwohin",""],
["2-2","カラオケボックス","karaoke-bokkusu","Karaokebox","N"],
["2-2","メモ","memo","Notiz","N"],
["2-2","うみ","umi","Meer","N"],
["2-2","（お）まつり","(o)matsuri","Fest, Volksfest","N"],
["2-2","ひる","hiru","Mittag, tagsüber","N"],
["2-2","はなびたいかい","hanabi-taikai","Feuerwerksfest","N"],

["2-3","きょう","kyoo","heute","N"],
["2-3","あした","ashita","morgen","N"],
["2-3","あさって","asatte","übermorgen","N"],
["2-3","きのう","kinoo","gestern","N"],
["2-3","おととい","ototoi","vorgestern","N"],
["2-3","こんしゅう","konshuu","diese Woche","N"],
["2-3","らいしゅう","raishuu","nächste Woche","N"],
["2-3","さらいしゅう","saraishuu","übernächste Woche","N"],
["2-3","せんしゅう","senshuu","letzte Woche","N"],
["2-3","せんせんしゅう","sensenshuu","vorletzte Woche","N"],
["2-3","こんげつ","kongetsu","dieser Monat","N"],
["2-3","らいげつ","raigetsu","nächster Monat","N"],
["2-3","さらいげつ","saraigetsu","übernächster Monat","N"],
["2-3","せんげつ","sengetsu","letzter Monat","N"],
["2-3","せんせんげつ","sensengetsu","vorletzter Monat","N"],
["2-3","ことし","kotoshi","dieses Jahr","N"],
["2-3","らいねん","rainen","nächstes Jahr","N"],
["2-3","さらいねん","sarainen","übernächstes Jahr","N"],
["2-3","きょねん","kyonen","letztes Jahr","N"],
["2-3","おととし","ototoshi","vorletztes Jahr","N"],
["2-3","こうえん","kooen","Park","N"],
["2-3","ジム","jimu","Fitnessstudio","N"],
["2-3","あさごはん","asagohan","Frühstück","N"],
["2-3","パン","pan","Brot","N"],
["2-3","くだもの","kudamono","Obst","N"],
["2-3","たまご","tamago","Ei","N"],
["2-3","たべます","tabemasu","essen","V"],
["2-3","のみます","nomimasu","trinken","V"],
["2-3","よみます","yomimasu","lesen","V"],
["2-3","ききます","kikimasu","hören, fragen","V"],
["2-3","かきます","kakimasu","schreiben","V",1],
["2-3","はなします","hanashimasu","sprechen","V"],
["2-3","みます","mimasu","sehen, anschauen","V"],
["2-3","かいます","kaimasu","kaufen","V"],
["2-3","とります","torimasu","fotografieren, aufnehmen","V"],
["2-3","つくります","tsukurimasu","machen, herstellen","V"],
["2-3","でんわ","denwa","Telefon, Anruf","N"],
["2-3","かけます","kakemasu","anrufen","V"],
["2-3","たばこ","tabako","Zigarette","N"],
["2-3","すいます","suimasu","rauchen","V"],
["2-3","おにぎり","onigiri","Onigiri, Reisball","N"],
["2-3","ひらがな","hiragana","Hiragana","N"],
["2-3","ぎゅうにゅう","gyuunyuu","Milch","N"],
["2-3","おんがく","ongaku","Musik","N"],
["2-3","（お）さけ","(o)sake","Alkohol, Sake","N"],
["2-3","まんが","manga","Manga","N"],
["2-3","テレビ","terebi","Fernseher","N"],
["2-3","ひるごはん","hirugohan","Mittagessen","N"],
["2-3","けさ","kesa","heute Morgen","N"],
["2-3","こんばん","konban","heute Abend","N"],
["2-3","ビール","biiru","Bier","N"],
["2-3","えいが","eega","Film","N"],
["2-3","なに","nani","was","N"],
["2-3","あなた","anata","du","N"],
["2-3","パーティー","paatii","Party","N"],
["2-3","します","shimasu","machen, tun","V",3],
["2-3","りょうり（を）します","ryoori(o) shimasu","kochen","V"],
["2-3","てんぷら","tenpura","Tempura","N"],
["2-3","ぎょうざ","gyooza","Gyōza, Teigtaschen","N"],
["2-3","いっしょに","isshoni","zusammen, gemeinsam",""],
["2-3","そうじ（を）します","sooji(o) shimasu","putzen, sauber machen","V"],
["2-3","サッカー","sakkaa","Fußball","N"],
["2-3","せんたく（を）します","sentaku(o) shimasu","Wäsche waschen","V"],
["2-3","かいもの（を）します","kaimono(o) shimasu","einkaufen","V"],
["2-3","（お）すし","(o)sushi","Sushi","N"],
["2-3","じゅんび（を）します","junbi(o) shimasu","vorbereiten","V"],
["2-3","ふく","fuku","Kleidung","N"],

/* ===== Topic 3 ===== */
["3-1","プレゼント","purezento","Geschenk","N"],
["3-1","あいます","aimasu","sich treffen","V"],
["3-1","います","imasu","haben (Belebtes, Besitz)","V"],
["3-1","タブレット","taburetto","Tablet","N"],
["3-1","じてんしゃ","jitensha","Fahrrad","N"],
["3-1","イヤホン","iyahon","Kopfhörer","N"],
["3-1","ぜんぶで","zenbude","insgesamt, zusammen",""],
["3-1","ふくろ","fukuro","Tüte, Beutel","N"],
["3-1","いります","irimasu","brauchen, benötigen","V"],
["3-1","エコバッグ","eko-baggu","Mehrwegtasche","N"],
["3-1","あります","arimasu","haben (Unbelebtes, Besitz)","V"],
["3-1","（お）かね","(o)kane","Geld","N"],
["3-1","ローマ","Rooma","Rom","N"],
["3-1","ハノイ","Hanoi","Hanoi","N"],
["3-1","ゲスト","gesuto","Gast","N"],

["3-2","みずうみ","mizuumi","See","N"],
["3-2","しま","shima","Insel","N"],
["3-2","かめ","kame","Schildkröte","N"],
["3-2","おおきい","ookii","groß","Aい"],
["3-2","あります（そんざい）","arimasu","es gibt, sich befinden (Unbelebtes)","V"],
["3-2","います（そんざい）","imasu","es gibt, sich befinden (Belebtes)","V"],
["3-2","みぎ","migi","rechts","N"],
["3-2","ひだり","hidari","links","N"],
["3-2","まえ","mae","vorne, davor","N"],
["3-2","うしろ","ushiro","hinten, dahinter","N"],
["3-2","うえ","ue","oben, darauf","N"],
["3-2","した","shita","unten, darunter","N"],
["3-2","なか","naka","innen, darin","N"],
["3-2","まんなか","mannaka","Mitte","N"],
["3-2","となり","tonari","daneben, nebenan","N"],
["3-2","ちかく","chikaku","in der Nähe","N"],
["3-2","あいだ","aida","dazwischen","N"],
["3-2","いち","ichi","Position, Lage","N"],
["3-2","もの","mono","Ding, Sache","N"],
["3-2","はこ","hako","Schachtel, Kiste","N"],
["3-2","つくえ","tsukue","Schreibtisch","N"],
["3-2","いす","isu","Stuhl","N"],
["3-2","ねこ","neko","Katze","N"],
["3-2","こうばん","kooban","Polizeiposten","N"],
["3-2","バスてい","basu-tee","Bushaltestelle","N"],
["3-2","ふんすい","funsui","Springbrunnen","N"],
["3-2","メルボルン","Meruborun","Melbourne","N"],
["3-2","とうぶ","toobu","Ostteil, östliche Region","N"],
["3-2","せいぶ","seebu","Westteil","N"],
["3-2","なんぶ","nanbu","Südteil","N"],
["3-2","ほくぶ","hokubu","Nordteil","N"],
["3-2","ちゅうぶ","chuubu","Zentralteil","N"],
["3-2","ひがし","higashi","Osten","N"],
["3-2","にし","nishi","Westen","N"],
["3-2","みなみ","minami","Süden","N"],
["3-2","きた","kita","Norden","N"],
["3-2","ミラノ","Mirano","Mailand","N"],
["3-2","シカゴ","Shikago","Chicago","N"],
["3-2","いけ","ike","Teich","N"],
["3-2","きょうかい","kyookai","Kirche","N"],
["3-2","いずみ","izumi","Quelle","N"],

/* ===== Topic 4 ===== */

["4-1","のりもの","norimono","Verkehrsmittel","N"],
["4-1","バス","basu","Bus","N"],
["4-1","やこうバス","yakoo-basu","Nachtbus","N"],
["4-1","しんかんせん","shinkansen","Shinkansen","N"],
["4-1","でんしゃ","densha","Zug, Bahn","N"],
["4-1","ちかてつ","chikatetsu","U-Bahn","N"],
["4-1","ひこうき","hikooki","Flugzeug","N"],
["4-1","ふね","fune","Schiff, Fähre","N"],
["4-1","タクシー","takushii","Taxi","N"],
["4-1","あるいて","aruite","zu Fuß (ohne で)",""],
["4-1","えき","eki","Bahnhof","N"],
["4-1","ホテル","hoteru","Hotel","N"],
["4-1","おおさか","Oosaka","Osaka","N"],
["4-1","きょうと","Kyooto","Kyoto","N"],
["4-1","ながの","Nagano","Nagano","N"],
["4-1","おきなわ","Okinawa","Okinawa","N"],
["4-1","かなざわ","Kanazawa","Kanazawa","N"],
["4-1","ほっかいどう","Hokkaidoo","Hokkaido","N"],
["4-1","きゅうしゅう","Kyuushuu","Kyushu","N"],
["4-1","しぶや","Shibuya","Shibuya","N"],
["4-1","しんじゅく","Shinjuku","Shinjuku","N"],
["4-1","かまくら","Kamakura","Kamakura","N"],
["4-1","びわこ","Biwako","Biwa-See","N"],
["4-1","にいがた","Niigata","Niigata","N"],
["4-1","あおもり","Aomori","Aomori","N"],
["4-1","よこはま","Yokohama","Yokohama","N"],
["4-1","だします","dashimasu","aufgeben, abschicken","V",1],
["4-1","かえします","kaeshimasu","zurückgeben","V"],
["4-1","およぎます","oyogimasu","schwimmen","V"],
["4-1","つり","tsuri","Angeln","N"],
["4-1","かいもの","kaimono","Einkaufen","N"],
["4-1","はなみ","hanami","Kirschblütenschau","N"],
["4-1","コンサート","konsaato","Konzert","N"],
["4-1","りょこう","ryokoo","Reise","N"],
["4-1","てがみ","tegami","Brief","N"],
["4-1","ばんごはん","bangohan","Abendessen","N"],
["4-1","はなび","hanabi","Feuerwerk","N"],
["4-1","ちゅうごくりょうり","chuugoku-ryoori","chinesisches Essen","N"],
["4-1","こたえ","kotae","Antwort","N"],
["4-1","なにで","nani de","womit",""],
["4-1","なにを しに","nani o shi ni","wozu, um was zu tun",""],
["4-1","やすい","yasui","günstig, billig","Aい"],
["4-1","そうですか","soo desu ka","ach so",""],

["4-3","しょうじょまんが","shoojo-manga","Shojo-Manga","N"],
["4-3","SFまんが","esu-efu-manga","Science-Fiction-Manga","N"],
["4-3","アニメ","anime","Anime","N"],
["4-3","ロック","rokku","Rockmusik","N"],
["4-3","スポーツ","supootsu","Sport","N"],
["4-3","テニス","tenisu","Tennis","N"],
["4-3","スキー","sukii","Skifahren","N"],
["4-3","ピアノ","piano","Klavier","N"],
["4-3","カラオケ","karaoke","Karaoke","N"],
["4-3","りょうり","ryoori","Kochen","N"],
["4-3","うた","uta","Gesang, Lied","N"],
["4-3","Tシャツ","tii-shatsu","T-Shirt","N"],
["4-3","とけい","tokee","Uhr","N"],
["4-3","くつ","kutsu","Schuhe","N"],
["4-3","ふるぎ","furugi","Secondhandkleidung","N"],
["4-3","はな","hana","Blume","N"],
["4-3","さいふ","saifu","Geldbörse","N"],
["4-3","にほんりょうり","nihon-ryoori","japanische Küche","N"],
["4-3","ラーメン","raamen","Ramen","N"],
["4-3","ぎゅうどん","gyuudon","Gyudon","N"],
["4-3","たこやき","takoyaki","Takoyaki","N"],
["4-3","なっとう","nattoo","Natto","N"],
["4-3","すき（な）","suki na","gern mögen","Aな"],
["4-3","じょうず（な）","joozu na","gut können","Aな"],
["4-3","へた（な）","heta na","schlecht können","Aな"],
["4-3","すてき（な）","suteki na","schön, toll","Aな"],
["4-3","きれい（な）","kiree na","schön, sauber","Aな"],
["4-3","ゆうめい（な）","yuumee na","berühmt","Aな"],
["4-3","ひま（な）","hima na","frei, Zeit habend","Aな"],
["4-3","ほしい","hoshii","haben wollen","Aい"],
["4-3","おもしろい","omoshiroi","interessant","Aい"],
["4-3","かっこいい","kakkoii","cool","Aい"],
["4-3","かるい","karui","leicht","Aい"],
["4-3","あたらしい","atarashii","neu","Aい"],
["4-3","おいしい","oishii","lecker","Aい"],
["4-3","はいります","hairimasu","hineingehen, baden","V"],

/* ===== Topic 5 ===== */

["5-2","あげます","agemasu","geben, schenken (an: に)","V"],
["5-2","もらいます","moraimasu","bekommen (von: に)","V"],
["5-2","かします","kashimasu","verleihen (an: に)","V",1],
["5-2","かります","karimasu","ausleihen (von: に)","V"],
["5-2","おしえます","oshiemasu","beibringen, lehren (an: に)","V",2],
["5-2","ならいます","naraimasu","lernen (von: に)","V"],
["5-2","わかります","wakarimasu","verstehen (Sache: が)","V"],
["5-2","マグカップ","magukappu","Tasse, Becher","N"],
["5-2","ペンケース","penkeesu","Federmäppchen","N"],
["5-2","はなたば","hanataba","Blumenstrauß","N"],
["5-2","バラ","bara","Rose","N"],
["5-2","ゆびわ","yubiwa","Ring","N"],
["5-2","マフラー","mafuraa","Schal","N"],
["5-2","ネクタイ","nekutai","Krawatte","N"],
["5-2","ネックレス","nekkuresu","Halskette","N"],
["5-2","ケーキ","keeki","Kuchen, Torte","N"],
["5-2","チョコレート","chokoreeto","Schokolade","N"],
["5-2","おとしだま","otoshidama","Neujahrsgeld für Kinder","N"],
["5-2","ぬいぐるみ","nuigurumi","Plüschtier","N"],
["5-2","おさら","osara","Teller","N"],
["5-2","はは","haha","(meine) Mutter","N"],
["5-2","ちち","chichi","(mein) Vater","N"],
["5-2","むすこ","musuko","(mein) Sohn","N"],
["5-2","こいびと","koibito","Partner, Partnerin, Liebste(r)","N"],
["5-2","ちゅうごくじん","chuugokujin","Chinese, Chinesin","N"],
["5-2","みんな","minna","alle","N"],
["5-2","ははの ひ","haha no hi","Muttertag","N"],
["5-2","ちちの ひ","chichi no hi","Vatertag","N"],
["5-2","クリスマス","kurisumasu","Weihnachten","N"],
["5-2","バレンタインデー","barentaindee","Valentinstag","N"],
["5-2","けっこんきねんび","kekkon-kinenbi","Hochzeitstag","N"],
["5-2","おしょうがつ","oshoogatsu","Neujahr","N"],
["5-2","もうすぐ","moosugu","bald",""],
["5-2","ちゅうごくご","chuugokugo","Chinesisch (Sprache)","N"],
["5-2","にほんご","nihongo","Japanisch (Sprache)","N"],
["5-2","いろ","iro","Farbe","N"],
["5-2","デザイン","dezain","Design","N"],
["5-2","トルコ","Toruko","Türkei","N"],

["5-3","かたづけます","katazukemasu","aufräumen","V",2],
["5-3","いれます","iremasu","hineintun, hineinstecken","V",2],
["5-3","つかいます","tsukaimasu","benutzen","V",1],
["5-3","おきます（おく）","okimasu","hinlegen, hinstellen","V",1],
["5-3","きります","kirimasu","abschalten, schneiden","V",1],
["5-3","とります（てに）","torimasu","nehmen, reichen","V",1],
["5-3","けします","keshimasu","ausschalten, löschen","V",1],
["5-3","あけます","akemasu","öffnen","V",2],
["5-3","しめます","shimemasu","schließen, zuziehen","V",2],
["5-3","つけます","tsukemasu","anschalten","V",2],
["5-3","みせます","misemasu","zeigen","V",2],
["5-3","はじめます","hajimemasu","anfangen","V",2],
["5-3","わすれます","wasuremasu","vergessen","V",2],
["5-3","もってきます","motte-kimasu","mitbringen","V",3],
["5-3","のり","nori","Klebstoff, Klebestift","N"],
["5-3","じょうぎ","joogi","Lineal","N"],
["5-3","ホッチキス","hotchikisu","Tacker, Hefter","N"],
["5-3","はさみ","hasami","Schere","N"],
["5-3","クリップ","kurippu","Büroklammer","N"],
["5-3","なまえ","namae","Name","N"],
["5-3","かんじ","kanji","Kanji, chinesisches Schriftzeichen","N"],
["5-3","よみかた","yomikata","Lesung, Leseweise","N"],
["5-3","まど","mado","Fenster","N"],
["5-3","カーテン","kaaten","Vorhang","N"],
["5-3","でんき","denki","Licht, Strom","N"],
["5-3","エアコン","eakon","Klimaanlage","N"],
["5-3","でんげん","dengen","Stromversorgung, Einschaltknopf","N"],
["5-3","これから","kore kara","ab jetzt, gleich",""],
["5-3","すみませんが","sumimasen ga","Entschuldigung, aber… (Bitteneinleitung)",""],
["5-3","どうしましたか","doo shimashita ka","Was ist los? Was gibt es?",""],
["5-3","わかりました","wakarimashita","verstanden, mach ich",""],
["5-3","いいですよ","ii desu yo","ja, gern (Zusage)",""],
["5-3","すこし","sukoshi","ein bisschen",""],
["5-3","ちょっと","chotto","ein wenig, kurz",""],
["5-3","あつい","atsui","heiß, warm","Aい"],
["5-3","さむい","samui","kalt","Aい"],
["5-3","あかい","akai","rot","Aい"]
];

const V = ROH.map(r => ({
  id: r[0] + "|" + r[1],
  ab: r[0],
  t: ABSCHNITTE[r[0]].t,
  kana: r[1],
  romaji: r[2],
  de: r[3],
  wa: r[4],
  gr: r[5] || 0     // Verbgruppe 1, 2 oder 3; 0 = noch nicht bekannt
}));

/* Vorhandene Topics, aus ABSCHNITTE abgeleitet. Für ein neues Topic genügen
   deshalb ein Eintrag oben in ABSCHNITTE und die Wörter in ROH - die App
   zieht Filter, Fortschritt und Listen von allein nach. */
const TOPICS = Object.keys(ABSCHNITTE)
  .map(function(a){ return ABSCHNITTE[a].t; })
  .filter(function(t, i, alle){ return alle.indexOf(t) === i; })
  .sort(function(a, b){ return a - b; });
