/* ------------------------------------------------------------------
   Vokabeldaten - ARC Kyoto, Topic 1 bis 3
   Aufbau je Zeile: [Abschnitt, Kana, Romaji, Bedeutung, Wortart]
   Wortart: N = Nomen, V = Verb, A = Adjektiv, leer = sonstiges
   ------------------------------------------------------------------ */

const ABSCHNITTE = {
  "1-1": { t: 1, nr: "§1", titel: "Vorstellung und Herkunft" },
  "1-2": { t: 1, nr: "§2", titel: "Räume und Orte" },
  "1-3": { t: 1, nr: "§3", titel: "これ・それ・あれ" },
  "1-4": { t: 1, nr: "§4", titel: "この・その・あの" },
  "2-1": { t: 2, nr: "§1", titel: "Uhrzeit und Tagesablauf" },
  "2-2": { t: 2, nr: "§2", titel: "Ferien und Termine" },
  "2-3": { t: 2, nr: "§3", titel: "Zeitangaben, Essen, Tätigkeiten" },
  "3-1": { t: 3, nr: "§1", titel: "Besitz und Einkauf" },
  "3-2": { t: 3, nr: "§2", titel: "Ort und Lage" }
};

const ROH = [
/* ===== Topic 1 ===== */
["1-1","みなさん","minasan","alle zusammen, meine Damen und Herren","N"],
["1-1","～さん","~san","Höflichkeitsanhang für Namen",""],
["1-1","かいしゃいん","kaishain","Firmenangestellter","N"],
["1-1","せんせい","sensee","Lehrer, Lehrerin","N"],
["1-1","きょうし","kyooshi","Lehrkraft (Berufsbezeichnung)","N"],
["1-1","がくせい","gakusee","Schüler, Student","N"],
["1-1","～じん","~jin","Anhang für Nationalitäten",""],
["1-1","ちゅうごく","Chuugoku","China","N"],
["1-1","イタリア","Itaria","Italien","N"],
["1-1","にほん","Nihon","Japan","N"],
["1-1","アメリカ","Amerika","USA","N"],
["1-1","わたし","watashi","ich","N"],
["1-1","はい","hai","ja",""],
["1-1","いいえ","iie","nein",""],
["1-1","りゅうがくせい","ryuugakusee","ausländischer Student","N"],
["1-1","にほんごがっこう","nihongo-gakkoo","Japanischschule","N"],
["1-1","せんもんがっこう","senmon-gakkoo","Fachschule, Berufsfachschule","N"],
["1-1","だいがくせい","daigakusee","Universitätsstudent","N"],
["1-1","だいがく","daigaku","Universität","N"],
["1-1","ふどうさん","fudoosan","Immobilien, Immobilienbüro","N"],
["1-1","しゃいん","shain","Angestellter einer Firma","N"],
["1-1","しゅっしん","shusshin","Herkunft, Heimatort","N"],
["1-1","シャンハイ","Shanhai","Shanghai","N"],
["1-1","ベトナム","Betonamu","Vietnam","N"],
["1-1","フランス","Furansu","Frankreich","N"],
["1-1","カナダ","Kanada","Kanada","N"],
["1-1","ブラジル","Burajiru","Brasilien","N"],
["1-1","ペキン","Pekin","Peking","N"],
["1-1","びょういん","byooin","Krankenhaus","N"],
["1-1","いしゃ","isha","Arzt","N"],
["1-1","タイ","Tai","Thailand","N"],
["1-1","バンコク","Bankoku","Bangkok","N"],
["1-1","パリ","Pari","Paris","N"],
["1-1","オーストラリア","Oosutoraria","Australien","N"],
["1-1","シドニー","Shidonii","Sydney","N"],
["1-1","めいし","meeshi","Visitenkarte","N"],
["1-1","ともだち","tomodachi","Freund, Freundin","N"],
["1-1","シアトル","Shiatoru","Seattle","N"],
["1-1","くに","kuni","Land, Heimatland","N"],
["1-1","がっこう","gakkoo","Schule","N"],
["1-1","かいしゃ","kaisha","Firma","N"],

["1-2","リビング","ribingu","Wohnzimmer","N"],
["1-2","ひじょうぐち","hijooguchi","Notausgang","N"],
["1-2","ここ","koko","hier","N"],
["1-2","そこ","soko","da (beim Gesprächspartner)","N"],
["1-2","あそこ","asoko","dort drüben","N"],
["1-2","キッチン","kicchin","Küche","N"],
["1-2","トイレ","toire","Toilette","N"],
["1-2","（お）ふろ","(o)furo","Bad, Badewanne","N"],
["1-2","シャワールーム","shawaa-ruumu","Duschraum","N"],
["1-2","ランドリールーム","randorii-ruumu","Waschraum","N"],
["1-2","ごみおきば","gomi-okiba","Müllsammelplatz","N"],
["1-2","どこ","doko","wo","N"],
["1-2","それから","sorekara","und dann, außerdem",""],
["1-2","ばしょ","basho","Ort, Platz","N"],
["1-2","そと","soto","draußen, außen","N"],
["1-2","きつえんじょ","kitsuenjo","Raucherbereich","N"],
["1-2","かいぎしつ","kaigi-shitsu","Besprechungsraum","N"],
["1-2","じどうはんばいき","jidoo-hanbaiki","Getränkeautomat","N"],
["1-2","ものおき","monooki","Abstellraum","N"],
["1-2","うけつけ","uketsuke","Empfang, Rezeption","N"],
["1-2","しょくどう","shokudoo","Kantine, Mensa","N"],

["1-3","これ","kore","dies hier","N"],
["1-3","それ","sore","das da (beim Gesprächspartner)","N"],
["1-3","あれ","are","das dort drüben","N"],
["1-3","（お）みやげ","(o)miyage","Mitbringsel, Souvenir","N"],
["1-3","どうぞ","doozo","bitte sehr, hier bitte",""],
["1-3","（お）ちゃ","(o)cha","Tee","N"],
["1-3","カードキー","kaado-kii","Kartenschlüssel","N"],
["1-3","かんこく","Kankoku","Südkorea","N"],
["1-3","おかし","okashi","Süßigkeiten, Knabbereien","N"],
["1-3","コーヒー","koohii","Kaffee","N"],
["1-3","キーホルダー","kiihorudaa","Schlüsselanhänger","N"],
["1-3","マグネット","magunetto","Magnet","N"],
["1-3","かばん","kaban","Tasche","N"],
["1-3","ほん","hon","Buch","N"],
["1-3","ざっし","zasshi","Zeitschrift","N"],
["1-3","ジュース","juusu","Saft","N"],
["1-3","スマホ","sumaho","Smartphone","N"],
["1-3","ゲーム","geemu","Spiel, Videospiel","N"],
["1-3","しゃしん","shashin","Foto","N"],
["1-3","みかん","mikan","Mandarine","N"],
["1-3","ワイン","wain","Wein","N"],
["1-3","にんぎょう","ningyoo","Puppe","N"],
["1-3","くるま","kuruma","Auto","N"],
["1-3","なん","nan","was","N"],
["1-3","（お）てら","(o)tera","buddhistischer Tempel","N"],
["1-3","え","e","Bild, Gemälde","N"],
["1-3","～ご","~go","Sprache (Anhang)",""],
["1-3","えいご","eego","Englisch","N"],
["1-3","ファッション","fasshon","Mode","N"],
["1-3","かぎ","kagi","Schlüssel","N"],
["1-3","レストラン","resutoran","Restaurant","N"],
["1-3","ポイントカード","pointo-kaado","Punktekarte, Kundenkarte","N"],
["1-3","シェアハウス","shea-hausu","Wohngemeinschaft","N"],
["1-3","へや","heya","Zimmer","N"],
["1-3","さとう","satoo","Zucker","N"],
["1-3","しお","shio","Salz","N"],
["1-3","～ごうしつ","~goo-shitsu","Zimmernummer (Anhang)","N"],
["1-3","なんごうしつ","nan-goo-shitsu","welche Zimmernummer","N"],
["1-3","でんわばんごう","denwa-bangoo","Telefonnummer","N"],
["1-3","なんばん","nan-ban","welche Nummer","N"],

["1-4","この","kono","dieser hier",""],
["1-4","その","sono","dieser da",""],
["1-4","あの","ano","jener dort",""],
["1-4","ペン","pen","Stift","N"],
["1-4","ぼうし","booshi","Hut, Mütze","N"],
["1-4","コップ","koppu","Becher, Glas","N"],
["1-4","ひと","hito","Person, Mensch","N"],
["1-4","だれ","dare","wer","N"],
["1-4","シャツ","shatsu","Hemd","N"],
["1-4","コート","kooto","Mantel","N"],
["1-4","かさ","kasa","Regenschirm","N"],
["1-4","けしごむ","keshigomu","Radiergummi","N"],
["1-4","おんなのこ","onna-no-ko","Mädchen","N"],
["1-4","～ちゃん","~chan","vertrauliche Anrede, meist für Mädchen",""],
["1-4","かわいい","kawaii","süß, niedlich","A"],
["1-4","～くん","~kun","vertrauliche Anrede, meist für Jungen",""],
["1-4","おとこのこ","otoko-no-ko","Junge","N"],
["1-4","ノート","nooto","Heft, Notizbuch","N"],
["1-4","ボールペン","boorupen","Kugelschreiber","N"],
["1-4","きょうかしょ","kyookasho","Lehrbuch","N"],
["1-4","えんぴつ","enpitsu","Bleistift","N"],
["1-4","わすれもの","wasuremono","vergessener Gegenstand, Fundsache","N"],

/* ===== Topic 2 ===== */
["2-1","いま","ima","jetzt","N"],
["2-1","じかん","jikan","Zeit, Stunde","N"],
["2-1","はん","han","halb","N"],
["2-1","ロンドン","Rondon","London","N"],
["2-1","ニューヨーク","Nyuuyooku","New York","N"],
["2-1","パース","Paasu","Perth","N"],
["2-1","リオデジャネイロ","Riodejaneiro","Rio de Janeiro","N"],
["2-1","まち","machi","Stadt, Ort","N"],
["2-1","じゅぎょう","jugyoo","Unterricht","N"],
["2-1","はじまります","hajimarimasu","beginnen","V"],
["2-1","おわります","owarimasu","enden, zu Ende gehen","V"],
["2-1","おきます","okimasu","aufstehen, aufwachen","V"],
["2-1","あさ","asa","Morgen","N"],
["2-1","まい～","mai~","jeden (Anhang)",""],
["2-1","ばん","ban","Abend","N"],
["2-1","ねます","nemasu","schlafen, schlafen gehen","V"],
["2-1","しごと","shigoto","Arbeit","N"],
["2-1","ギター","gitaa","Gitarre","N"],
["2-1","レッスン","ressun","Unterrichtsstunde, Kurs","N"],
["2-1","はたらきます","hatarakimasu","arbeiten","V"],
["2-1","ごぜん","gozen","vormittags","N"],
["2-1","ごご","gogo","nachmittags","N"],
["2-1","よる","yoru","Nacht","N"],
["2-1","としょかん","toshokan","Bibliothek","N"],
["2-1","びじゅつかん","bijutsukan","Kunstmuseum","N"],
["2-1","ゆうびんきょく","yuubinkyoku","Post","N"],
["2-1","ぎんこう","ginkoo","Bank","N"],
["2-1","べんきょうします","benkyoo-shimasu","lernen, studieren","V"],
["2-1","やすみます","yasumimasu","Pause machen, frei haben","V"],
["2-1","ホーチミン","Hoochimin","Ho-Chi-Minh-Stadt","N"],
["2-1","モスクワ","Mosukuwa","Moskau","N"],
["2-1","デパート","depaato","Kaufhaus","N"],
["2-1","カフェ","kafe","Café","N"],

["2-2","やすみ","yasumi","freier Tag, Urlaub","N"],
["2-2","カレンダー","karendaa","Kalender","N"],
["2-2","いつ","itsu","wann",""],
["2-2","テスト","tesuto","Test, Prüfung","N"],
["2-2","アルバイト","arubaito","Nebenjob","N"],
["2-2","ごみのひ","gomi-no-hi","Mülltag","N"],
["2-2","たんじょうび","tanjoobi","Geburtstag","N"],
["2-2","はるやすみ","haru-yasumi","Frühlingsferien","N"],
["2-2","なつやすみ","natsu-yasumi","Sommerferien","N"],
["2-2","ふゆやすみ","fuyu-yasumi","Winterferien","N"],
["2-2","ゴールデンウィーク","gooruden-wiiku","Golden Week","N"],
["2-2","うち／いえ","uchi / ie","Zuhause, Haus","N"],
["2-2","いきます","ikimasu","gehen, fahren","V"],
["2-2","きます","kimasu","kommen","V"],
["2-2","かえります","kaerimasu","nach Hause gehen, zurückkehren","V"],
["2-2","スーパー","suupaa","Supermarkt","N"],
["2-2","どこも","dokomo","nirgendwohin",""],
["2-2","カラオケボックス","karaoke-bokkusu","Karaokebox","N"],
["2-2","メモ","memo","Notiz","N"],
["2-2","うみ","umi","Meer","N"],
["2-2","（お）まつり","(o)matsuri","Fest, Volksfest","N"],
["2-2","ひる","hiru","Mittag, tagsüber","N"],
["2-2","はなびたいかい","hanabi-taikai","Feuerwerksfest","N"],

["2-3","きょう","kyoo","heute","N"],
["2-3","あした","ashita","morgen","N"],
["2-3","あさって","asatte","übermorgen","N"],
["2-3","きのう","kinoo","gestern","N"],
["2-3","おととい","ototoi","vorgestern","N"],
["2-3","こんしゅう","konshuu","diese Woche","N"],
["2-3","らいしゅう","raishuu","nächste Woche","N"],
["2-3","さらいしゅう","saraishuu","übernächste Woche","N"],
["2-3","せんしゅう","senshuu","letzte Woche","N"],
["2-3","せんせんしゅう","sensenshuu","vorletzte Woche","N"],
["2-3","こんげつ","kongetsu","dieser Monat","N"],
["2-3","らいげつ","raigetsu","nächster Monat","N"],
["2-3","さらいげつ","saraigetsu","übernächster Monat","N"],
["2-3","せんげつ","sengetsu","letzter Monat","N"],
["2-3","せんせんげつ","sensengetsu","vorletzter Monat","N"],
["2-3","ことし","kotoshi","dieses Jahr","N"],
["2-3","らいねん","rainen","nächstes Jahr","N"],
["2-3","さらいねん","sarainen","übernächstes Jahr","N"],
["2-3","きょねん","kyonen","letztes Jahr","N"],
["2-3","おととし","ototoshi","vorletztes Jahr","N"],
["2-3","こうえん","kooen","Park","N"],
["2-3","ジム","jimu","Fitnessstudio","N"],
["2-3","あさごはん","asagohan","Frühstück","N"],
["2-3","パン","pan","Brot","N"],
["2-3","くだもの","kudamono","Obst","N"],
["2-3","たまご","tamago","Ei","N"],
["2-3","たべます","tabemasu","essen","V"],
["2-3","のみます","nomimasu","trinken","V"],
["2-3","よみます","yomimasu","lesen","V"],
["2-3","ききます","kikimasu","hören, fragen","V"],
["2-3","かきます","kakimasu","schreiben","V"],
["2-3","はなします","hanashimasu","sprechen","V"],
["2-3","みます","mimasu","sehen, anschauen","V"],
["2-3","かいます","kaimasu","kaufen","V"],
["2-3","とります","torimasu","fotografieren, aufnehmen","V"],
["2-3","つくります","tsukurimasu","machen, herstellen","V"],
["2-3","でんわ","denwa","Telefon, Anruf","N"],
["2-3","かけます","kakemasu","anrufen","V"],
["2-3","たばこ","tabako","Zigarette","N"],
["2-3","すいます","suimasu","rauchen","V"],
["2-3","おにぎり","onigiri","Onigiri, Reisball","N"],
["2-3","ひらがな","hiragana","Hiragana","N"],
["2-3","ぎゅうにゅう","gyuunyuu","Milch","N"],
["2-3","おんがく","ongaku","Musik","N"],
["2-3","（お）さけ","(o)sake","Alkohol, Sake","N"],
["2-3","まんが","manga","Manga","N"],
["2-3","テレビ","terebi","Fernseher","N"],
["2-3","ひるごはん","hirugohan","Mittagessen","N"],
["2-3","けさ","kesa","heute Morgen","N"],
["2-3","こんばん","konban","heute Abend","N"],
["2-3","ビール","biiru","Bier","N"],
["2-3","えいが","eega","Film","N"],
["2-3","なに","nani","was","N"],
["2-3","あなた","anata","du","N"],
["2-3","パーティー","paatii","Party","N"],
["2-3","します","shimasu","machen, tun","V"],
["2-3","りょうり（を）します","ryoori(o) shimasu","kochen","V"],
["2-3","てんぷら","tenpura","Tempura","N"],
["2-3","ぎょうざ","gyooza","Gyōza, Teigtaschen","N"],
["2-3","いっしょに","isshoni","zusammen, gemeinsam",""],
["2-3","そうじ（を）します","sooji(o) shimasu","putzen, sauber machen","V"],
["2-3","サッカー","sakkaa","Fußball","N"],
["2-3","せんたく（を）します","sentaku(o) shimasu","Wäsche waschen","V"],
["2-3","かいもの（を）します","kaimono(o) shimasu","einkaufen","V"],
["2-3","（お）すし","(o)sushi","Sushi","N"],
["2-3","じゅんび（を）します","junbi(o) shimasu","vorbereiten","V"],
["2-3","ふく","fuku","Kleidung","N"],

/* ===== Topic 3 ===== */
["3-1","プレゼント","purezento","Geschenk","N"],
["3-1","あいます","aimasu","sich treffen","V"],
["3-1","います","imasu","haben (Belebtes, Besitz)","V"],
["3-1","タブレット","taburetto","Tablet","N"],
["3-1","じてんしゃ","jitensha","Fahrrad","N"],
["3-1","イヤホン","iyahon","Kopfhörer","N"],
["3-1","ぜんぶで","zenbude","insgesamt, zusammen",""],
["3-1","ふくろ","fukuro","Tüte, Beutel","N"],
["3-1","いります","irimasu","brauchen, benötigen","V"],
["3-1","エコバッグ","eko-baggu","Mehrwegtasche","N"],
["3-1","あります","arimasu","haben (Unbelebtes, Besitz)","V"],
["3-1","（お）かね","(o)kane","Geld","N"],
["3-1","ローマ","Rooma","Rom","N"],
["3-1","ハノイ","Hanoi","Hanoi","N"],
["3-1","ゲスト","gesuto","Gast","N"],

["3-2","みずうみ","mizuumi","See","N"],
["3-2","しま","shima","Insel","N"],
["3-2","かめ","kame","Schildkröte","N"],
["3-2","おおきい","ookii","groß","A"],
["3-2","あります（そんざい）","arimasu","es gibt, sich befinden (Unbelebtes)","V"],
["3-2","います（そんざい）","imasu","es gibt, sich befinden (Belebtes)","V"],
["3-2","みぎ","migi","rechts","N"],
["3-2","ひだり","hidari","links","N"],
["3-2","まえ","mae","vorne, davor","N"],
["3-2","うしろ","ushiro","hinten, dahinter","N"],
["3-2","うえ","ue","oben, darauf","N"],
["3-2","した","shita","unten, darunter","N"],
["3-2","なか","naka","innen, darin","N"],
["3-2","まんなか","mannaka","Mitte","N"],
["3-2","となり","tonari","daneben, nebenan","N"],
["3-2","ちかく","chikaku","in der Nähe","N"],
["3-2","あいだ","aida","dazwischen","N"],
["3-2","いち","ichi","Position, Lage","N"],
["3-2","もの","mono","Ding, Sache","N"],
["3-2","はこ","hako","Schachtel, Kiste","N"],
["3-2","つくえ","tsukue","Schreibtisch","N"],
["3-2","いす","isu","Stuhl","N"],
["3-2","ねこ","neko","Katze","N"],
["3-2","こうばん","kooban","Polizeiposten","N"],
["3-2","バスてい","basu-tee","Bushaltestelle","N"],
["3-2","ふんすい","funsui","Springbrunnen","N"],
["3-2","メルボルン","Meruborun","Melbourne","N"],
["3-2","とうぶ","toobu","Ostteil, östliche Region","N"],
["3-2","せいぶ","seebu","Westteil","N"],
["3-2","なんぶ","nanbu","Südteil","N"],
["3-2","ほくぶ","hokubu","Nordteil","N"],
["3-2","ちゅうぶ","chuubu","Zentralteil","N"],
["3-2","ひがし","higashi","Osten","N"],
["3-2","にし","nishi","Westen","N"],
["3-2","みなみ","minami","Süden","N"],
["3-2","きた","kita","Norden","N"],
["3-2","ミラノ","Mirano","Mailand","N"],
["3-2","シカゴ","Shikago","Chicago","N"],
["3-2","いけ","ike","Teich","N"],
["3-2","きょうかい","kyookai","Kirche","N"],
["3-2","いずみ","izumi","Quelle","N"]
];

const V = ROH.map(r => ({
  id: r[0] + "|" + r[1],
  ab: r[0],
  t: ABSCHNITTE[r[0]].t,
  kana: r[1],
  romaji: r[2],
  de: r[3],
  wa: r[4]
}));
